BOARD_USES_QCOM_HARDWARE := true
TARGET_USES_QCOM_BSP := true

COMMON_GLOBAL_CFLAGS += -DBOARD_HAS_SENSORS_GROUP

TARGET_QCOM_DISPLAY_VARIANT := caf-msm8992
TARGET_QCOM_AUDIO_VARIANT := caf-msm8992
TARGET_QCOM_MEDIA_VARIANT := caf-msm8992
TARGET_ENABLE_QC_AV_ENHANCEMENTS := true

TARGET_RIL_VARIANT := caf

BOARD_USES_QC_TIME_SERVICES := true

# Increase coldboot timeout
TARGET_INCREASES_COLDBOOT_TIMEOUT := true

# Init
TARGET_INIT_VENDOR_LIB := libinit_ether
TARGET_RECOVERY_DEVICE_MODULES := libinit_ether

# Power
TARGET_POWERHAL_VARIANT := qcom

# Added to indicate that protobuf-c is supported in this build
PROTOBUF_SUPPORTED := true

# Enable peripheral manager
TARGET_PER_MGR_ENABLED := true

TARGET_KEYMASTER_WAIT_FOR_QSEE := true
